version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    container_name: symfony-fundamentals-web
    volumes: 
      - ".:/app"
    restart: on-failure
    ports:
      - "8001:8000"
    tty: true
    depends_on:
      - db
    links:
      - db
    networks:
      - symfony-fundamentals-web-network
  db:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    container_name: symfony-fundamentals-web-db
    env_file:
      - mysql.env
    ports:
      - "3306:3306"
    volumes:
      - "./mysql_volume:/var/lib/mysql"
    networks:
      - symfony-fundamentals-web-network
networks:
  symfony-fundamentals-web-network:
    driver: bridge