apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-01-29T19:10:20Z"
  generation: 1
  labels:
    app: symfony-fundamentals-web
  name: symfony-fundamentals-web
  namespace: default
  resourceVersion: "9381"
  uid: 7499a9cc-2e42-4b27-ad62-d4e893930fb9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: symfony-fundamentals-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: symfony-fundamentals-web
    spec:
      containers:
      - image: caprilespe/symfony-fundamentals-web:v1
        imagePullPolicy: IfNotPresent
        name: symfony-fundamentals-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-29T19:11:33Z"
    lastUpdateTime: "2022-01-29T19:11:33Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-29T19:10:20Z"
    lastUpdateTime: "2022-01-29T19:11:33Z"
    message: ReplicaSet "symfony-fundamentals-web-6f5f59556f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
