apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-01-29T19:13:26Z"
  labels:
    app: symfony-fundamentals-web
  name: symfony-fundamentals-web
  namespace: default
  resourceVersion: "9465"
  uid: 7fb62254-96d6-4843-8892-78cbf5bd087e
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.88.114
  clusterIPs:
  - 10.110.88.114
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30394
    port: 8001
    protocol: TCP
    targetPort: 8000
  selector:
    app: symfony-fundamentals-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
